"""initial migration

Revision ID: 88dd897f88a7
Revises: 
Create Date: 2022-01-16 18:15:24.959927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88dd897f88a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('record_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), server_default='No Description Provided', nullable=True),
    sa.Column('cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flasklogin-users.id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_name')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flasklogin-users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('records')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
